language: node_js
node_js:
  - "12.6"
before_install:
  - rvm install 2.6.3
install:
  - gem install bundler
  - npm install
before_script:
  - bundle install
  - npm install -g firebase-tools
script:
  - bundle exec jekyll build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
  - npm run lh --perf=85 --a11y=85 --bp=85 --seo=85 https://csh-public-site.web.app
