// Mobile Bootstrap Header
//Designed by: Brandon Hudson
// Date: 10 14 14
/* Handles the content of the header as the page is resized. 
Dynamically changes the contents of the header div to mobile
bootstrap header when screen width is under 768 pixels.
*/

	// Handle Responsive design changes dynamically
	
	//Perform on page load
	$(document).ready(function(){
		if ($(window).width() <= 767){ //for mobile users
		document.getElementById("header").innerHTML = ' <div class="navbar navbar-default nav-custom navbar-fixed-top" role="navigation"> <div class="container"> <div class="navbar-header"> <a href="./"><!--<img src="images/logo.png" alt="Computer Science House" width="117" height="50"/> --> <img src="logo.png" alt="CSH" width="94" height="40" class="logo"></a> <button type="button" class="navbar-toggle collapsed " data-toggle="collapse" data-target=".navbar-collapse"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button> <!--PUT THE LOGO HERE --> </div> <div class="navbar-collapse collapse"> <ul class="nav navbar-nav" align="center"> <li><a href="./"<?php if (calledFrom() == "index") { ?>class="active"<?php } ?> >Home</a></li> <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" <?php if (calledFrom() == "about") { ?>class="active"<?php } ?> > <span class="caret"></span> About <span class="caret"></span></a> <ul class="dropdown-menu" role="menu"> <li align="center"><a href="about.php">Who Are We?</a></li> <li class="divider"></li> <li align="center"><a href="projects.php">Projects</a></li> <li class="divider"></li> <li align="center"><a href="alumni.php">Alumni</a></li> <li class="divider"></li> <li align="center"><a href="eboard.php">Eboard</a></li> <li class="divider"></li> </ul> </li> <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" <?php if ( calledFrom() == "membership") { ?>class="active"<?php } ?>><span class="caret"></span> Membership <span class="caret"></span></a> <ul class="dropdown-menu" role="menu"> <li align="center"><a href="membership.php">Membership Information</a></li> <li class="divider"></li> <li align="center"><a href="traditions.php">Traditions</a></li> <li class="divider"></li> <li align="center"><a href="tour.php">Tour</a></li> <li class="divider"></li> </ul> </li> <li><a href="contact.php" <?php if ( calledFrom() == "contact") { ?>class="active"<?php } ?>>Contact</a></li> </ul> </div><!--/.nav-collapse --> </div> </div>';
	}
	else{ //for everyone else (desktop clients)
		document.getElementById("header").innerHTML = ' <div class="wrapper"><a href="./"><img src="images/logo.png" alt="Computer Science House" width="117" height="50"/></a><ul id="nav"><li><a href="./" <?php if (calledFrom() == "index") { ?>class="selected"<?php } ?> >Home</a></li><li><a href="about.php" <?php if (calledFrom() == "about") { ?>class="selected"<?php } ?>>About</a> <ul><li><a href="projects.php">Projects</a></li><li><a href="alumni.php">Alumni</a></li><li><a href="eboard.php">Eboard</a></li></ul></li><li><a href="membership.php" <?php if ( calledFrom() == "membership") { ?>class="selected"<?php } ?>>Membership</a><ul><li><a href="traditions.php">Traditions</a></li><li><a href="tour.php">Tour</a></li><!--<li><a href="scholarship.php">Scholarship</a></li>--></ul></li><li ><a href="contact.php" <?php if ( calledFrom() == "contact") { ?>class="selected"<?php } ?>>Contact</a></li></ul></div>';
	}
	});
		
		//Perform when page changes size
	$(window).resize(function resizer() {
	if ($(window).width() <= 767){ //for mobile users
		document.getElementById("header").innerHTML = ' <div class="navbar navbar-default nav-custom navbar-fixed-top" role="navigation"> <div class="container"> <div class="navbar-header"> <a href="./"><!--<img src="images/logo.png" alt="Computer Science House" width="117" height="50"/> --> <img src="logo.png" alt="CSH" width="94" height="40" class="logo"></a> <button type="button" class="navbar-toggle collapsed " data-toggle="collapse" data-target=".navbar-collapse"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button> <!--PUT THE LOGO HERE --> </div> <div class="navbar-collapse collapse"> <ul class="nav navbar-nav" align="center"> <li><a href="./"<?php if (calledFrom() == "index") { ?>class="active"<?php } ?> >Home</a></li> <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" <?php if (calledFrom() == "about") { ?>class="active"<?php } ?> > <span class="caret"></span> About <span class="caret"></span></a> <ul class="dropdown-menu" role="menu"> <li align="center"><a href="about.php">Who Are We?</a></li> <li class="divider"></li> <li align="center"><a href="projects.php">Projects</a></li> <li class="divider"></li> <li align="center"><a href="alumni.php">Alumni</a></li> <li class="divider"></li> <li align="center"><a href="eboard.php">Eboard</a></li> <li class="divider"></li> </ul> </li> <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" <?php if ( calledFrom() == "membership") { ?>class="active"<?php } ?>><span class="caret"></span> Membership <span class="caret"></span></a> <ul class="dropdown-menu" role="menu"> <li align="center"><a href="membership.php">Membership Information</a></li> <li class="divider"></li> <li align="center"><a href="traditions.php">Traditions</a></li> <li class="divider"></li> <li align="center"><a href="tour.php">Tour</a></li> <li class="divider"></li> </ul> </li> <li><a href="contact.php" <?php if ( calledFrom() == "contact") { ?>class="active"<?php } ?>>Contact</a></li> </ul> </div><!--/.nav-collapse --> </div> </div>';
	}
	else{ //for everyone else (desktop clients)
		document.getElementById("header").innerHTML = ' <div class="wrapper"><a href="./"><img src="images/logo.png" alt="Computer Science House" width="117" height="50"/></a><ul id="nav"><li><a href="./" <?php if (calledFrom() == "index") { ?>class="selected"<?php } ?> >Home</a></li><li><a href="about.php" <?php if (calledFrom() == "about") { ?>class="selected"<?php } ?>>About</a> <ul><li><a href="projects.php">Projects</a></li><li><a href="alumni.php">Alumni</a></li><li><a href="eboard.php">Eboard</a></li></ul></li><li><a href="membership.php" <?php if ( calledFrom() == "membership") { ?>class="selected"<?php } ?>>Membership</a><ul><li><a href="traditions.php">Traditions</a></li><li><a href="tour.php">Tour</a></li><!--<li><a href="scholarship.php">Scholarship</a></li>--></ul></li><li ><a href="contact.php" <?php if ( calledFrom() == "contact") { ?>class="selected"<?php } ?>>Contact</a></li></ul></div>';
	}
	});