
name: Lighthouse Performance

on:
  pull_request:
    branches: [ master ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit develop using Lighthouse
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: https://wwwtest.csh.rit.edu
          uploadArtifacts: true
          temporaryPublicStorage: true
